document.addEventListener("DOMContentLoaded", function () {
    // Array of tips
    const tipsForTheYear = [
        "Start your year with a positive mindset. Set realistic goals and take small steps each day to achieve them.",
        "Stay hydrated! Drink enough water to keep your body and mind functioning at their best.",
        "Practice gratitude. Take a moment each day to appreciate the positive aspects of your life.",
        "Prioritize self-care. Take time for activities that bring you joy and relaxation.",
        "Learn something new. Expand your knowledge and skills in areas that interest you.",
        "Practice active listening. Truly engage in conversations by giving your full attention to others.",
        "Get moving! Incorporate physical activity into your day for improved health and well-being.",
        "Connect with loved ones. Nurture relationships that bring joy and support into your life.",
        "Set boundaries. Know when to say no and prioritize your well-being.",
        "Embrace change. Life is full of transitions, and adapting can lead to personal growth.",
        "Take breaks. Allow yourself moments of rest to recharge and maintain productivity.",
        "Practice mindfulness. Be present in the moment and appreciate the now.",
        "Express gratitude. Let the people around you know that you appreciate them.",
        "Read a book. Engage your mind with literature that inspires, educates, or entertains.",
        "Declutter your space. A tidy environment can contribute to a clearer mind.",
        "Practice deep breathing. Incorporate moments of calm and relaxation into your day.",
        "Set achievable goals. Break larger tasks into smaller, manageable steps.",
        "Stay positive. Focus on solutions rather than dwelling on problems.",
        "Try a new hobby. Discover activities that bring you joy and fulfillment.",
        "Connect with nature. Spend time outdoors for a refreshing perspective.",
        "Express kindness. Small acts of kindness can have a big impact on others.",
        "Reflect on your achievements. Acknowledge and celebrate your progress.",
        "Practice patience. Understand that progress takes time, and be patient with yourself and others.",
        "Get enough sleep. Quality sleep is essential for overall well-being.",
        "Learn from mistakes. View challenges as opportunities for growth.",
        "Practice gratitude. Reflect on the positive aspects of your day.",
        "Connect with others. Foster meaningful relationships in both personal and professional spheres.",
        "Embrace creativity. Allow yourself to explore and express your creative side.",
        "Set boundaries. Establish limits to protect your time and energy.",
        "Focus on the present. Don't let worries about the future overshadow your current moments.",
        "Celebrate achievements. Recognize and appreciate your accomplishments, big and small.",
        "Celebrate the small victories. Acknowledge and take pride in even the smallest accomplishments.",
        "Express your creativity through art, writing, or any other form that brings you joy.",
        "Take a digital detox. Unplug from screens for a designated period to promote mindfulness.",
        "Practice positive affirmations. Remind yourself of your strengths and capabilities.",
        "Learn a new skill online. There are countless resources to acquire new knowledge.",
        "Volunteer your time or support a charitable cause. Giving back is fulfilling.",
        "Create a budget. Manage your finances to reduce stress and achieve financial goals.",
        "Try a new recipe. Cooking can be a fun and rewarding experience.",
        "Practice effective time management. Prioritize tasks and use your time wisely.",
        "Explore your local community. Discover hidden gems and appreciate your surroundings.",
        "Take a moment to appreciate nature's beauty. Find joy in the simplicity of the outdoors.",
        "Start a journal. Reflect on your thoughts, experiences, and personal growth.",
        "Listen to uplifting music. Music has the power to influence your mood positively.",
        "Practice good posture. Maintain a healthy posture to support physical and mental well-being.",
        "Attend a cultural event. Immerse yourself in different perspectives and experiences.",
        "Learn to say 'thank you' in a new language. Cultivate an appreciation for diversity.",
        "Practice forgiveness. Let go of grudges and focus on healing and moving forward.",
        "Set realistic expectations. Avoid setting yourself up for unnecessary stress by being realistic.",
        "Try meditation. Cultivate mindfulness and a sense of inner peace.",
        "Stay curious. Approach the world with a sense of wonder and a desire to learn.",
        "Express your thoughts and feelings openly. Communication is key to healthy relationships.",
        "Celebrate your uniqueness. Embrace the qualities that make you who you are.",
        "Explore a new genre of books, movies, or music. Expand your cultural horizons.",
        "Invest in quality sleep. Create a calming bedtime routine for better rest.",
        "Practice empathy. Seek to understand the perspectives and feelings of others.",
        "Learn a new dance move. Movement is not only fun but also great for physical health.",
        "Plan a future trip. Dreaming and planning for the future can be exciting.",
        "Reflect on your values. Ensure that your actions align with your core beliefs.",
        "Try a new form of exercise. Keep physical activity engaging and enjoyable.",
        "Practice mindful eating. Pay attention to the flavors and textures of your meals.",
        "Connect with a mentor or role model. Learn from those who inspire you.",
        "Express your gratitude to someone who has made a difference in your life.",
        "Celebrate the arrival of a new season. Find joy in the changes in nature.",
        "Practice positive self-talk. Replace negative thoughts with encouraging affirmations.",
        "Set aside time for a hobby you love. Engaging in hobbies is a form of self-care.",
        "Revisit a childhood favorite. Nostalgia can bring joy and happy memories.",
        "Spend quality time with pets. The companionship of animals can be therapeutic.",
        "Visualize success. Envisioning positive outcomes can boost confidence and motivation.",
        "Attend a live performance. Whether it's theater, music, or dance, enjoy the arts.",
        "Practice digital decluttering. Organize and streamline your digital space.",
        "Create a vision board. Visualize your goals and aspirations through images and words.",
        "Practice random acts of kindness. Spread positivity by doing something nice for others.",
        "Reflect on your personal growth. Acknowledge how far you've come.",
        "Set aside time for relaxation. Allow yourself moments of peace and quiet.",
        "Connect with a friend you haven't spoken to in a while. Nurture friendships.",
        "Express your love to family members. Share your feelings and appreciation.",
        "Celebrate your achievements from the past month. Acknowledge your hard work.",
        "Plan a self-care day. Dedicate a day to activities that bring you joy and relaxation.",
        "Set new goals for the upcoming month. Keep pushing yourself to grow and evolve.",
        "Practice resilience. Learn to bounce back from challenges with strength and optimism.",
        "Engage in a digital detox day. Take a break from screens to promote mental well-being.",
        "Try a new form of exercise. Keep your physical routine interesting and challenging.",
        "Reflect on your favorite quotes. Words of wisdom can inspire and motivate.",
        "Practice the 2-minute rule. If a task takes less than 2 minutes, do it immediately.",
        "Create a vision for the future. Envision the life you want to lead and set goals accordingly.",
        "Experiment with a new hairstyle or outfit. Change can be refreshing.",
        "Learn a relaxation technique, such as deep breathing or progressive muscle relaxation.",
        "Volunteer your time to a cause you're passionate about. Make a positive impact.",
        "Practice effective goal-setting. Break down big goals into smaller, achievable steps.",
        "Engage in a mindfulness meditation session. Focus on your breath and be present.",
        "Explore a new podcast. Find topics that educate and entertain.",
        "Organize a virtual game night with friends. Stay connected and have fun.",
        "Write a letter to your future self. Reflect on your aspirations and growth.",
        "Create a gratitude jar. Fill it with notes about things you're thankful for.",
        "Try a new type of cuisine. Expand your palate and culinary skills.",
        "Set boundaries with technology. Designate specific times for screen use.",
        "Take a scenic walk or hike. Enjoy the beauty of nature and get some exercise.",
        "Experiment with a new hobby. Discover hidden talents and interests.",
        "Plan a DIY project. Engage in creative activities for a sense of accomplishment.",
        "Practice positive body language. Stand tall and project confidence.",
        "Learn a relaxation technique, such as guided imagery or visualization.",
        "Reflect on a meaningful quote each morning. Carry the inspiration with you throughout the day.",
        "Experiment with a new workout routine. Keep your fitness regimen diverse.",
        "Participate in a virtual workshop or webinar. Continue learning and growing.",
        "Write down your goals for the week. Stay organized and focused.",
        "Create a bedtime ritual for better sleep. Wind down and relax before bedtime.",
        "Experiment with a new form of art. Draw, paint, or sculpt for self-expression.",
        "Practice positive thinking. Challenge negative thoughts with optimistic alternatives.",
        "Organize your workspace for improved productivity. A tidy space can lead to a clear mind.",
        "Engage in a reflective journaling session. Explore your thoughts and feelings.",
        "Take a break from social media. Enjoy the present moment without distractions.",
        "Try a new type of tea or coffee. Savor the flavors and enjoy a relaxing moment.",
        "Explore a local museum or art gallery. Immerse yourself in culture and history.",
        "Practice a digital photo detox. Organize and back up your digital photos.",
        "Plan a virtual movie night with friends. Share the experience of watching a film together.",
        "Try a new mindfulness app. Incorporate guided meditations into your routine.",
        "Engage in a spontaneous act of kindness. Brighten someone's day with a gesture.",
        "Explore a new park or outdoor space. Connect with nature and enjoy fresh air.",
        "Start a habit of nightly stretching. Improve flexibility and relax your muscles.",
        "Experiment with a new productivity technique. Find what works best for you.",
        "Create a playlist of uplifting songs. Music can influence your mood positively.",
        "Try a new form of relaxation, such as aromatherapy or a hot bath.",
        "Participate in a virtual fitness class. Stay active and motivated.",
        "Experiment with a new recipe using seasonal ingredients. Enjoy the flavors of the season.",
        "Reflect on a favorite childhood memory. Cherish the positive moments from your past.",
        "Plan a virtual book club meeting. Discuss and share thoughts on your latest read.",
        "Experiment with a new language-learning app. Expand your linguistic skills.",
        "Create a personal mission statement. Clarify your values and aspirations.",
        "Set aside time for a digital declutter session. Streamline your digital life.",
        "Try a new form of creative writing. Express yourself through poetry, stories, or journaling.",
        "Explore a nearby town or neighborhood you haven't visited. Discover new places.",
        "Practice mindfulness while eating. Savor each bite and enjoy the sensory experience.",
        "Experiment with a new form of exercise, such as yoga or pilates.",
        "Participate in a virtual trivia night with friends. Test your knowledge and have fun.",
        "Try a new form of meditation, such as loving-kindness meditation.",
        "Reflect on your proudest accomplishments. Celebrate your achievements.",
        "Plan a virtual coffee or tea date with a friend. Connect despite physical distance.",
        "Experiment with a new art technique, such as pointillism or collage.",
        "Create a list of personal affirmations. Repeat them daily for a positive mindset.",
        "Participate in a community clean-up event. Contribute to a cleaner environment.",
        "Try a new form of relaxation, such as progressive muscle relaxation.",
        "Reflect on a valuable life lesson. Consider how challenges have shaped you.",
        "Experiment with a new type of workout, such as high-intensity interval training (HIIT).",
        "Practice the Pomodoro Technique for improved focus and productivity.",
        "Plan a virtual game night with family. Strengthen bonds through play.",
        "Try a new form of self-care, such as a facial mask or aromatherapy.",
        "Experiment with a new hobby, such as gardening or photography.",
        "Create a playlist of motivational podcasts. Listen to inspiring stories and insights.",
        "Participate in a virtual dance class. Have fun while staying active.",
        "Try a new mindfulness practice, such as body scan meditation.",
        "Reflect on the positive qualities of a role model. Incorporate them into your life.",
        "Experiment with a new form of journaling, such as bullet journaling.",
        "Practice gratitude for the simple pleasures in life. Focus on the small joys.",
        "Plan a virtual cooking class with friends. Learn and create together.",
        "Try a new form of artistic expression, such as digital art or photography.",
        "Participate in a virtual fitness challenge with friends. Stay motivated together.",
        "Experiment with a new form of relaxation, such as autogenic training.",
        "Reflect on your favorite childhood books. Revisit the magic of storytelling.",
        "Plan a virtual karaoke night with friends. Sing and enjoy a lively time together.",
        "Try a new form of mental exercise, such as puzzles or brain games.",
        "Practice deep breathing exercises for relaxation and stress reduction.",
        "Create a vision board for the upcoming month. Visualize your goals.",
        "Participate in a virtual poetry reading. Share your favorite poems with others.",
        "Try a new form of outdoor activity, such as paddleboarding or hiking.",
        "Experiment with a new form of creative expression, such as abstract art.",
        "Reflect on your favorite childhood games. Rediscover the joy of play.",
        "Plan a virtual museum tour with friends. Explore art and culture together.",
        "Try a new form of relaxation",
    ];

    // Get the current day of the year
    const dayOfYear = new Date().getDay();

    // Use the day of the year to select a tip
    const randomTipIndex = dayOfYear % tipsForTheYear.length;
    const randomTip = tipsForTheYear[randomTipIndex];

    // Display the random tip on the webpage
    const tipTextElement = document.getElementById("tip-text");
    tipTextElement.textContent = randomTip;
});